SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_ASM_COMPILER_FORCED TRUE)
SET(CMAKE_C_COMPILER_FORCED   TRUE)
SET(CMAKE_CXX_COMPILER_FORCED TRUE)

SET(TOOLCHAIN_DIR $ENV{ARMGCC_DIR})

SET(CMAKE_C_COMPILER   "${TOOLCHAIN_DIR}/bin/arm-none-eabi-gcc")
SET(CMAKE_CXX_COMPILER "${TOOLCHAIN_DIR}/bin/arm-none-eabi-g++")
SET(CMAKE_ASM_COMPILER "${TOOLCHAIN_DIR}/bin/arm-none-eabi-gcc")

SET(CMAKE_OBJCOPY "${TOOLCHAIN_DIR}/bin/arm-none-eabi-objcopy" CACHE INTERNAL "")
SET(CMAKE_OBJDUMP "${TOOLCHAIN_DIR}/bin/arm-none-eabi-objdump" CACHE INTERNAL "")
SET(CMAKE_SIZE    "${TOOLCHAIN_DIR}/bin/arm-none-eabi-size"    CACHE INTERNAL "")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
